#if !canImport(ObjectiveC)
import XCTest

extension CodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableTests = [
        ("testCanBeDecodedFromJSON", testCanBeDecodedFromJSON),
        ("testCanBeEncodedToJSON", testCanBeEncodedToJSON),
        ("testIsIdenticalAfterEncodingAndDecoding", testIsIdenticalAfterEncodingAndDecoding),
    ]
}

extension OptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionsTests = [
        ("testAllowCommentsAndWhitespaceAllowsCommentsAndWhitespaces", testAllowCommentsAndWhitespaceAllowsCommentsAndWhitespaces),
        ("testAnchorsMatchLinesCanAnchorMatchesToTheStartOfEachLine", testAnchorsMatchLinesCanAnchorMatchesToTheStartOfEachLine),
        ("testDotMatchesLineSeparatorsAllowsDotToMatchNewlines", testDotMatchesLineSeparatorsAllowsDotToMatchNewlines),
        ("testIgnoreCaseEnablesALowercasePatternToMatchUppercaseInput", testIgnoreCaseEnablesALowercasePatternToMatchUppercaseInput),
        ("testIgnoreCaseEnablesAnUppercasePatternToMatchLowercaseInput", testIgnoreCaseEnablesAnUppercasePatternToMatchLowercaseInput),
        ("testIgnoreMetacharactersTreatsMetacharactersAsLiterals", testIgnoreMetacharactersTreatsMetacharactersAsLiterals),
    ]
}

extension RegexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegexTests = [
        ("testRegexCanMatchMultipleTimesInTheSameString", testRegexCanMatchMultipleTimesInTheSameString),
        ("testRegexCaptureRangesCorrectlyConvertFromUnderlyingIndexType", testRegexCaptureRangesCorrectlyConvertFromUnderlyingIndexType),
        ("testRegexDoesNotIncludeEntireMatchInCaptureList", testRegexDoesNotIncludeEntireMatchInCaptureList),
        ("testRegexLastMatchIsAvailableInPatternMatchingContext", testRegexLastMatchIsAvailableInPatternMatchingContext),
        ("testRegexLastMatchResetsLastMatchToNilWhenMatchFails", testRegexLastMatchResetsLastMatchToNilWhenMatchFails),
        ("testRegexMatchesMultipleCaptureGroups", testRegexMatchesMultipleCaptureGroups),
        ("testRegexMatchesSingleCaptureGroup", testRegexMatchesSingleCaptureGroup),
        ("testRegexMatchesWithNoCaptureGroups", testRegexMatchesWithNoCaptureGroups),
        ("testRegexOptionatCaptureGroupsMaintainCapturePositionRegardlessOfOptionality", testRegexOptionatCaptureGroupsMaintainCapturePositionRegardlessOfOptionality),
        ("testRegexOptionatCaptureGroupsReturnNilForUnmatchedCaptures", testRegexOptionatCaptureGroupsReturnNilForUnmatchedCaptures),
        ("testRegexProvidesAccessToCaptureRanges", testRegexProvidesAccessToCaptureRanges),
        ("testRegexProvidesAccessToTheEntireMatchedString", testRegexProvidesAccessToTheEntireMatchedString),
        ("testRegexProvidesAccessToTheMatchedRange", testRegexProvidesAccessToTheMatchedRange),
        ("testRegexSupportsMatchOperator", testRegexSupportsMatchOperator),
        ("testRegexWhenMatchingAtLineAnchorsCanAnchorMatchesToTheStartOfEachLine", testRegexWhenMatchingAtLineAnchorsCanAnchorMatchesToTheStartOfEachLine),
        ("testRegexWhenMatchingAtLineAnchorsValidatesReadmeExampleIsCorrect", testRegexWhenMatchingAtLineAnchorsValidatesReadmeExampleIsCorrect),
        ("testValidateReadmeExampleForCaptureRanges", testValidateReadmeExampleForCaptureRanges),
    ]
}

extension StringReplacementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringReplacementTests = [
        ("testReadmeExampleReformatsAGreeting", testReadmeExampleReformatsAGreeting),
        ("testReplaceAllMatchingReplacesAllMatchesWithinTheGivenString", testReplaceAllMatchingReplacesAllMatchesWithinTheGivenString),
        ("testReplaceAllMatchingReplacesTemplateVariablesWithTheCorrespondingCaptureGroup", testReplaceAllMatchingReplacesTemplateVariablesWithTheCorrespondingCaptureGroup),
        ("testReplaceFirstMatchingReplacesTemplateVariablesWithTheCorrespondingCaptureGroup", testReplaceFirstMatchingReplacesTemplateVariablesWithTheCorrespondingCaptureGroup),
        ("testReplaceFirstMatchingReplacesTheFirstMatchWithTheGivenString", testReplaceFirstMatchingReplacesTheFirstMatchWithTheGivenString),
        ("testReplacingWithAShorterString", testReplacingWithAShorterString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableTests.__allTests__CodableTests),
        testCase(OptionsTests.__allTests__OptionsTests),
        testCase(RegexTests.__allTests__RegexTests),
        testCase(StringReplacementTests.__allTests__StringReplacementTests),
    ]
}
#endif
